wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1677252723.278295
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
activation:
  desc: null
  value: ReLU
dropout:
  desc: null
  value: 0.5
hidden_layer_sizes:
  desc: null
  value:
  - 32
  - 64
kernel_sizes:
  desc: null
  value:
  - 3
num_classes:
  desc: null
  value: 10
pool_sizes:
  desc: null
  value:
  - 2
